name = "bit_sets_example"
description = "An example of using bit_sets for use in development and testing"
version = "1.0.0"

authors = ["Michael Hardeman"]
maintainers = ["Michael Hardeman <mhardeman25@gmail.com>"]
maintainers-logins = ["michael-hardeman"]
licenses = "GPL-2.0-or-later"
website = "https://github.com/michael-hardeman/bit_sets"
tags = []

executables = ["main"]

[[depends-on]]
bit_sets = "~1.0.0"

[[pins]]
bit_sets = { path='../bit_sets' }
