name = "bit_sets"
description = "A packed boolean array that saves space and is preformant"
version = "1.0.0"

authors = ["Michael Hardeman"]
maintainers = ["Michael Hardeman <mhardeman25@gmail.com>"]
maintainers-logins = ["michael-hardeman"]
licenses = "GPL-2.0-or-later"
website = "https://github.com/michael-hardeman/bit_sets"
tags = ["bit", "set", "boolean", "array", "packed", "preformance"]
